//Zertop™
//www.zertop.com
package GUI;

import Engine.Config;

public class LauncherGUI extends javax.swing.JFrame {  
    
    public LauncherGUI() {
        initComponents();
        versionLable.setText("Version: "+Config.getVersion());
        LauncherPanel.setVisible (true);
    }
    
    public static void setUpdateText (String text)
    {
        updatesText.setText(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LauncherPanel = new javax.swing.JPanel();
        updatesText = new javax.swing.JLabel();
        versionLable = new javax.swing.JLabel();
        ImageLogo = new javax.swing.JLabel();
        ImageBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zertop's LineTool");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 450));
        setName("Zertop's LineTool"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LauncherPanel.setBackground(new java.awt.Color(255, 255, 255));
        LauncherPanel.setMaximumSize(new java.awt.Dimension(650, 450));
        LauncherPanel.setMinimumSize(new java.awt.Dimension(650, 450));
        LauncherPanel.setPreferredSize(new java.awt.Dimension(650, 450));
        LauncherPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatesText.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        updatesText.setForeground(new java.awt.Color(255, 255, 255));
        updatesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatesText.setText("Checking for updates");
        LauncherPanel.add(updatesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 210, -1));

        versionLable.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        versionLable.setForeground(new java.awt.Color(255, 255, 255));
        versionLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionLable.setText("Version: ");
        LauncherPanel.add(versionLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 100, -1));

        ImageLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/logo.png"))); // NOI18N
        LauncherPanel.add(ImageLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        ImageBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/back.jpg"))); // NOI18N
        LauncherPanel.add(ImageBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, -60, -1, -1));

        getContentPane().add(LauncherPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageBack;
    private javax.swing.JLabel ImageLogo;
    private javax.swing.JPanel LauncherPanel;
    private static javax.swing.JLabel updatesText;
    private javax.swing.JLabel versionLable;
    // End of variables declaration//GEN-END:variables
}
